.vscode/launch.json, CHANGELOG.md, CONTRIBUTING.md, README.md, client/src/extension.ts, package.json, server/package-lock.json, server/package.json, server/src/codeActions.ts, server/src/server.ts
- Upgrade to npm-groovy-lint v3.1.3
- Hide GroovyLint status bar item when the active VsCode file is not Groovy code (and if no GroovyLint action in progress)
- Add screenshot image in README
- Add CONTRIBUTING section
- Fix issue when creating/updating .groovylintrc.js file when the VsCode Workspace has multiple folders
- Fix tabs navigation issue
=> Updates / fixes

package.json, server/src/clientUtils.ts
- Fix blocking issue when using QuickFix Action (source was not replaced). If someone knows how to make good automated tests for a VsCode extension, please contact me !
- Change README
=> Fix blocking QuickAction issue + README

.circleci/config.yml, CHANGELOG.md, README.md, client/src/test/runTest.ts, client/src/test/suite/extension.test.ts, package.json, server/package-lock.json, server/package.json, server/src/clientUtils.ts, server/src/codeActions.ts, server/src/linter.ts, server/src/linterParser.ts
- Warn user in case of fix error(s) failures, and advise to do so manually
- Improve QuickFix action performances
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v3.2.3
- Improve performances
- Fix indentation when rules IfStatementBraces or ElseBlockBraces are corrected during a format or a fix
- Fixes
- Infinite spinner when using QuickFix "Fix in all file"
=> QuickFix perfs, debug, code coverage (see details)

CHANGELOG.md, server/src/codeActions.ts
- Improve QuickFix actions labels
=> Improve QuickFix actions labels

CHANGELOG.md, README.md, client/src/test/suite/extension.test.ts, package.json, server/src/DocumentsManager.ts, server/src/clientUtils.ts, server/src/codeActions.ts, server/src/folder.ts, server/src/linter.ts, server/src/linterParser.ts, server/src/server.ts
- Add setting **groovyLint.debug.enable** : Display more logs in VsCode Output panel (select "GroovyLint") for issue investigation
- Update settings definition in README documentation
=> Debug mode + doc

server/package-lock.json, server/package.json
=> Update npm-groovy-lint to 4.5.0

CHANGELOG.md, README.md, server/package-lock.json, server/package.json
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v4.12.0
- Improve performances and compatibility
=> Improve performances and compatibilty

CHANGELOG.md, README.md, server/package-lock.json, server/package.json, server/src/linter.ts
- Troubleshoot Java installation issue
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v4.14.0
=> Java troubleshooting

CHANGELOG.md, README.md, server/package-lock.json, server/package.json, server/src/DocumentsManager.ts, server/src/linter.ts
- Fixes
- Issue when requesting lints too quickly just after the extension is launched [(#51)](https://github.com/nvuillam/vscode-groovy-lint/issues/51)
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v5.0.3
- Updated fix rules
- Indentation
- IndentationClosingBrace
=> Fix startup issue & Indentation rules

CHANGELOG.md, README.md, server/package-lock.json, server/package.json
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v5.4.1
- CodeNarcServer listens to localhost only [(#59)](https://github.com/nvuillam/npm-groovy-lint/pull/59) solving [(#56)](https://github.com/nvuillam/npm-groovy-lint/issues/56)
=> Upgrade to npm-groovy-lint v5.4.1

CHANGELOG.md, README.md, server/package-lock.json, server/package.json
- Fix part of [(#66)](https://github.com/nvuillam/vscode-groovy-lint/issues/66) Problem using on VSCode on macOS
=> Fix bug on macOS

CHANGELOG.md, README.md, server/package-lock.json, server/package.json
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v7.2.0
- Upgrade[java-caller](https://www.npmjs.com/package/java-caller) to v2.0.0 : better performances
=> Upgrade npm-groovy-lint to 7.2.0 (better perfs)

.circleci/config.yml, CHANGELOG.md, README.md, server/package-lock.json, server/package.json
=> Fix run on Windows when username contains space(s)

CHANGELOG.md, package.json, server/package-lock.json, server/package.json
- Add .nf and .gradle extensions
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v7.5.0
=> Add .nf and .gradle extensions

CHANGELOG.md, README.md, server/package-lock.json, server/package.json, server/src/linter.ts
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v7.5.2
- Fix crash when empty groovy file 
- Fix crash when non-sense groovy file (Fixes #66 )
=> Fix crashes

CHANGELOG.md, README.md, server/package-lock.json, server/package.json
- Upgrade to [npm-groovy-lint](https://www.npmjs.com/package/npm-groovy-lint) v7.5.4
=> Upgrade to npm-groovy-lint v7.5.4

CHANGELOG.md, server/package-lock.json, server/package.json
Upgrade cli-progress to avoid [colors lib boring but harmless hack](https://github.com/Marak/colors.js/issues/285)
=> Upgrade  npm-groovy-lint to v9.3.2

README.md
Correcting Shit -> Shift in ReadMe
=> Correcting profanity typo

CHANGELOG.md, package-lock.json, server/package-lock.json, server/package.json
=> Upgrade to npm-groovy-lint 9.5.0 + other dependencies

.cspell.json, .github/workflows/mega-linter.yml, CHANGELOG.md, server/package-lock.json, server/package.json
Fixes https://github.com/nvuillam/vscode-groovy-lint/issues/200
=> Upgrade npm-groovy-lint

CHANGELOG.md, server/package-lock.json, server/package.json
Fixes https://github.com/nvuillam/vscode-groovy-lint/issues/217
=> Upgrade npm-groovy-lint to fix issues with Mac
